# Generated by Django 5.1.7 on 2025-03-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('total_fund_needed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_fund_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('visitor_type', models.CharField(choices=[('guest', 'Guest'), ('delivery', 'Delivery Person'), ('service', 'Service Provider'), ('other', 'Other')], max_length=20)),
                ('visiting_flat', models.CharField(max_length=10)),
                ('resident_name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('car', 'Car'), ('on_foot', 'On Foot')], max_length=10)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('security_guard', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
