# Generated by Django 5.1.7 on 2025-03-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_visitor_delete_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='resident_name',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='security_guard',
        ),
    ]
