# Generated by Django 5.1.7 on 2025-03-20 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_visitor_resident_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visiting_flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
    ]
