# Generated by Django 5.1.7 on 2025-03-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_expense_contribution_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='screenshot',
            field=models.ImageField(upload_to='payment_proofs/'),
        ),
    ]
