# Generated by Django 5.1.7 on 2025-03-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='facility',
            old_name='price_per_hour',
            new_name='price_per_day',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2025-12-13'),
            preserve_default=False,
        ),
    ]
