# Generated by Django 5.1.7 on 2025-03-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_maintenancepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='received_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
