# Generated by Django 5.1.7 on 2025-03-21 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_income_received_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='transaction_id',
        ),
    ]
